2015/10/19 05:30:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection.connectionString cannot be empty.' in C:\Data\XAMPP\yii\framework\db\CDbConnection.php:387
Stack trace:
#0 C:\Data\XAMPP\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Data\XAMPP\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Data\XAMPP\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Data\XAMPP\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Data\XAMPP\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Data\XAMPP\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Data\XAMPP\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Data\XAMPP\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Data\XAMPP\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Data\XAMPP\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Data\XAMPP\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Data\XAMPP\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Data\XAMPP\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Data\XAMPP\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Data\XAMPP\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\Data\XAMPP\htdocs\yii\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/index.php?r=gii/default/index
---
2015/10/19 05:40:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection.connectionString cannot be empty.' in C:\Data\XAMPP\yii\framework\db\CDbConnection.php:387
Stack trace:
#0 C:\Data\XAMPP\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Data\XAMPP\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Data\XAMPP\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Data\XAMPP\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Data\XAMPP\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Data\XAMPP\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Data\XAMPP\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Data\XAMPP\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Data\XAMPP\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Data\XAMPP\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Data\XAMPP\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Data\XAMPP\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Data\XAMPP\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Data\XAMPP\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Data\XAMPP\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\Data\XAMPP\htdocs\yii\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/index.php?r=gii/default/index
---
2015/10/19 05:49:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\Data\XAMPP\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Data\XAMPP\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\Data\XAMPP\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\Data\XAMPP\htdocs\yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/index.php?r=user
---
